import { AIProvider } from '@/types';

export const AI_PROVIDERS: AIProvider[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    subtitle: 'OpenAI',
    model: 'gpt-4o',
    primaryColor: '#10A37F',
    secondaryColor: '#0D8C6D',
    accentColor: '#1AE5A8',
    textColor: '#FFFFFF',
    icon: 'chatbubble-ellipses',
    gradientColors: ['#0D8C6D', '#10A37F', '#19C897'],
    isAvailable: true,
    badge: 'GPT-4o',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    subtitle: 'Google DeepMind',
    model: 'gemini-1.5-pro',
    primaryColor: '#4285F4',
    secondaryColor: '#1A73E8',
    accentColor: '#8AB4F8',
    textColor: '#FFFFFF',
    icon: 'sparkles',
    gradientColors: ['#1A73E8', '#4285F4', '#34A8EB'],
    isAvailable: true,
    badge: '1.5 Pro',
  },
  {
    id: 'claude',
    name: 'Claude',
    subtitle: 'Anthropic',
    model: 'claude-3-5-sonnet',
    primaryColor: '#CC785C',
    secondaryColor: '#B5622A',
    accentColor: '#F0A07A',
    textColor: '#FFFFFF',
    icon: 'logo-octocat',
    gradientColors: ['#B5622A', '#CC785C', '#E8946E'],
    isAvailable: true,
    badge: 'Sonnet 3.5',
  },
  {
    id: 'llama',
    name: 'Llama',
    subtitle: 'Meta AI',
    model: 'llama-3.1-405b',
    primaryColor: '#7C3AED',
    secondaryColor: '#6D28D9',
    accentColor: '#A78BFA',
    textColor: '#FFFFFF',
    icon: 'cube',
    gradientColors: ['#6D28D9', '#7C3AED', '#9D5FFF'],
    isAvailable: true,
    badge: '405B',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    subtitle: 'Mistral AI',
    model: 'mistral-large',
    primaryColor: '#FF7000',
    secondaryColor: '#E56000',
    accentColor: '#FF9A40',
    textColor: '#FFFFFF',
    icon: 'flame',
    gradientColors: ['#E56000', '#FF7000', '#FF9A40'],
    isAvailable: true,
    badge: 'Large',
  },
  {
    id: 'grok',
    name: 'Grok',
    subtitle: 'xAI',
    model: 'grok-2',
    primaryColor: '#1C1C1C',
    secondaryColor: '#111111',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    icon: 'flash',
    gradientColors: ['#111111', '#1C1C1C', '#2A2A2A'],
    isAvailable: true,
    badge: 'Grok 2',
  },
];

export const CARD_PEEK_HEIGHT = 22;
export const CARD_SCALE_DECREMENT = 0.04;
export const CARD_VERTICAL_OFFSET = 14;
export const MAX_VISIBLE_STACK = 3;
